"""empty message

Revision ID: 0637f3192773
Revises: ea970a1696ac
Create Date: 2019-12-15 17:35:40.137811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0637f3192773'
down_revision = 'ea970a1696ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_request_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('remote_addr', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('user_agent', sa.String(length=100), nullable=True),
    sa.Column('remote_user', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_request_log_timestamp'), 'application_request_log', ['timestamp'], unique=False)
    op.drop_index('ix_steel_processing_timestamp', table_name='steel_processing')
    op.create_index(op.f('ix_steel_processing_timestamp'), 'steel_processing', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_steel_processing_timestamp'), table_name='steel_processing')
    op.create_index('ix_steel_processing_timestamp', 'steel_processing', ['timestamp'], unique=1)
    op.drop_index(op.f('ix_application_request_log_timestamp'), table_name='application_request_log')
    op.drop_table('application_request_log')
    # ### end Alembic commands ###
