"""empty message

Revision ID: ea970a1696ac
Revises: 
Create Date: 2019-12-14 20:46:14.873391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea970a1696ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('steel_processing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_steel_processing_temperature'), 'steel_processing', ['temperature'], unique=False)
    op.create_index(op.f('ix_steel_processing_timestamp'), 'steel_processing', ['timestamp'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_steel_processing_timestamp'), table_name='steel_processing')
    op.drop_index(op.f('ix_steel_processing_temperature'), table_name='steel_processing')
    op.drop_table('steel_processing')
    # ### end Alembic commands ###
